name: Environment Setup
description: 'Setup PNPM and Node'
runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9.5.0
    - name: Set up NodeJS v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install npm modules
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
