name: PR Commit
on:
  pull_request:
    branches: [main]
jobs:
  prettier-format:
    name: Prettier Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3
      - name: Set up NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Check code format
        run: pnpm run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3
      - name: Set up NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Lint source code
        run: npm run lint
      - name: Lint commits
        run: npx commitlint --verbose --from=origin/main

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3
      - name: Set up NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Run unit tests
        run: npm run test

  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3
      - name: Set up NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install npm modules
        run: pnpm install
      - name: Build library
        run: npm run build
